### ISSUE TITLE
Add kselftest to Gentoo KernelCI

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/GBuildbot#28]
https://kselftest.wiki.kernel.org/start

**Comment by rperier** [comment]
+1
See also https://linux-test-project.github.io, this is complementary to kselftest imho.

**Comment by aliceinwire** [comment]
we already talked about ltp, I think in the wiki. so is already planned.

**Comment by aliceinwire** [comment]
currently working on:
https://github.com/GKernelCI/Ghelper/tree/kselftest

**Comment by aliceinwire** [comment]
kselftest need udhcp connectiong for testing
http://140.211.166.173:10080/scheduler/job/185#L791

**Comment by aliceinwire** [comment]
pull request sended https://github.com/GKernelCI/Ghelper/pull/6
