### ISSUE TITLE
Documentation for test workflow

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/GBuildbot#51]
We need documentation
- how to reproduce the environment
- how to connect a worker to the main buildbot server

**Comment by aliceinwire** [comment]
@mjeveritt

**Comment by mjeveritt** [comment]
I think this is a good idea, and having been through the process (And will repeat soon on a new system) I am happy to do this.
Two pointers/suggestions:-
- I think it would be helpful to create a 'docs' folder in the repo with salient setup information (perhaps some of the design intentions, functional description of the setup ie. triggers, builders, etc
- We can utilise the in-repo wiki to make a MD "how-to" to share setup information, references to any relevant online resources, etc, which are harder to render in pure text in the 'docs' folder above.

**Comment by kuzetsa** [comment]
as mentioned on issue #71, I'm setting up a public kanban to help track my workflow:

> will be using github "issues" and/or kanban-type project
> tracking tools for collaboration (_transparency_) and
> transferring the documentation to a gentoo-managed
> wiki / project space / Gentoo_kernelCI should be easier
> if the workflow is tracked in a more public & visible way.
> 
> _...rather than an undocumented, quick & dirty "hack"_

the process for setting up the tooling ([tuleap](https://www.tuleap.org/)) is tricky, so  
I'll be documenting that procedure as well. short version is:

* VPS image or container is highly recommended
  * CentoOS / RHEL via KVM is well-supported  
(*far easier if using ansible*)
  * docker requires experience with docker
  * if using bare-metal OS, breakage results in
  an undefined state with no way to uninstall,  
  repair, or reinstall (*unsupported by upstream*)

there are too many (*undocumented*) "quick & dirty hacks",  
so making my own work more transparent is where I'll start.

(*fully documenting the steps to provision the framework  
itself will be the first documentation task done on tuleap*)

**Comment by aliceinwire** [comment]
looks nice!

**Comment by kuzetsa** [comment]
**From #gentoo-kernel, freenode:**

```
[18:21:21] <kuzetsa> this looks like it's on infrastructure
.  operated by a neutral 3rd party
```

I think this is fine, and more-or-less free from conflicts of interest:

https://github.com/gentoo/Gentoo_kernelCI/projects

(*as much as I'd like for something to exist on gentoo infrastructure, I haven't had time to set up a test environment for anything which could be reproduced and installed as a gentoo-controlled tool*)

**Comment by aliceinwire** [comment]
@kuzetsa kanboard is so nice ! :)

**Comment by aliceinwire** [comment]
we are currently using the github kanboard for organizing and github readme for the documentation  https://github.com/orgs/GKernelCI/projects/2
