### ISSUE TITLE
Document arm testing enviroment installation procedure

### ISSUE THREAD

**Issue by aliceinwire** [GKernelCI/GBuildbot#62]

**Comment by kuzetsa** [comment]
the current amd64 boot test is done using qcow image:

http://distfiles.gentoo.org/experimental/amd64/openstack/

I didn't see the analogous arm-type one available:

http://distfiles.gentoo.org/experimental/arm/openstack/

so perhaps a very minimalist boot tester like in this footnote:

https://github.com/gentoo/Gentoo_kernelCI/issues/59#issuecomment-404922199

intended / specific details for arm test need to be decided, I think

```
# using a cross toolchain for arm testing
  293  crossdev -S -t armv7a-hardfloat-linux-gnueabi
# confirmed nothing "weird" was recently modified:
  319  history | grep crossdev
# need kernel source to test the cross-toolchain:
  322  emerge '=sys-kernel/gentoo-sources-4.17.4'
# noticed it's not stable, so therefore did this:
  323  cd /etc/portage/package.keywords/
  326  nano -w crosscompile_kernel_arm 
  327  eshowkw gentoo-sources
# //still// need kernel source to actually test this:
  329  emerge '=sys-kernel/gentoo-sources-4.17.4'
# details for compiling a kernel omitted (for now)

[...]

# creating minimalist payload for qemu boot test:
  385  emerge-armv7a-hardfloat-linux-gnueabi busybox
# basic checking to make sure everyhing is good:
  386  cd /usr/armv7a-hardfloat-linux-gnueabi/
  387  ls
  388  cd bin
  389  ls
  391  cd ..
  392  ls
  393  cd var/db/pkg/
  394  ls
  395  cd sys-apps/
  396  ls
  397  cd ..
  400  ls -ld /usr/armv7a-hardfloat-linux-gnueabi/var/db/pkg/*/*
  401  cd
# some of the mistakes are ommitted here
  435  find . | cpio -R root:root -H newc -o | gzip > ~/armpayload-initramfs.gz

[...]  

# busybox uses symlinks, traditionaly in /bin/
  467  cd armpayload-qemu/
  468  ls
  469  mkdir bin
  470  mv * bin
  471  ls
  472  ls
  473  cd bin/
# busybox symlinks in /bin, but NOT "init" itself
  475  mv init ..

[...]

# make sure everything is clean this time (oops)
  483  rm armpayload-initramfs.gz 
  484  cd armpayload-qemu/
# make last revisions / finalize "init" script:
  488  nano -w init 
# create the initramfs itself
  493  find . | cpio -R root:root -H newc -o | gzip > ~/armpayload-initramfs.gz
# ^ to document which commands were used:
  501  history
```

^ this type of initramfs can be used with qemu

a good qemu version (for arm) looks like this one:

https://github.com/gentoo/Gentoo_kernelCI/issues/61#issuecomment-404766929

example boot tester, documented above:

```
#!/bin/sh
# This script created by AQEMU
/usr/bin/qemu-system-arm -kernel $1 \
-initrd armpayload-initramfs.gz \
-machine virt -nographic -serial mon:stdio
```

A single argument is passed to this script:

just the name of the kernel, such as the compiled one  
mentioned in the history entry 329 (*see above*)

not sure how this compares to buildbot's method

```
#!/bin/sh
make \
ARCH=arm CROSS_COMPILE=armv7a-hardfloat-linux-gnueabi- \
--jobs 18 --load-average 19.9
```

note: there are a few ways to generate a .config  
(*board-specific defconfigs for arm are common*)

**Comment by kuzetsa** [comment]
The specific init script I wrote is ugly:

https://mouses.xyz/~kuzetsa/gentoo_tmp/arm_kernel_test.log

minimalist test for the kernel itself, but lacks  
the usual sensible / graceful behavior on exit

note the kernel panic on exit... dot dot dot
...it's a known outcome for "lazy" init scripts.

this version is in gentoo's tree: sys-process/dumb-init  
(*haven't tested, but it's more robust and graceful*)

other possible alternatives:

sys-apps/sysvinit (*with openrc*) or systemd, etc.

quote from preceding comment:
> intended / specific details for arm test need to be decided, I think

**Comment by kuzetsa** [comment]
Tried to reproduce this environment today... dot dot dot

Discovered a gap in the documentation.  
this is more correct (and more concise)

```

emerge-armv7a-hardfloat-linux-gnueabi busybox

[...]

last few lines of output contain:

Using system located in ROOT tree /usr/armv7a-hardfloat-linux-gnueabi/

>>> No outdated packages were found on your system.
```

followed by:

```
mkdir ./armpayload-qemu/
./armpayload-qemu/bin/
cp -P /usr/armv7a-hardfloat-linux-gnueabi/bin/* ./armpayload-qemu/bin/
nano -w ./armpayload-qemu/init 
```

github now offers the option to review past revisions of comments.
I'll editing the earlier / above comment for brevity.

**Comment by aliceinwire** [comment]
arm as been added in the testing enviroments
