### ISSUE TITLE
ARM kernel config missing CONFIG_NET

### ISSUE THREAD

**Issue by mjeveritt** [GKernelCI/GBuildbot#66]
`Patch_kernel` and `build_kernel` both contain warnings about missing dependencies on CONFIG_NET. This results in a failure to build the kernel image and the resulting trickle-down failures.
I suggest we create a patched _defconfig which is used by the `patch_kernel` script.

**Comment by aliceinwire** [comment]
arm kernel is currently booting correctly with gentoo stage 3 image
