### ISSUE TITLE
feature parity for arm VS amd64 testing

### ISSUE THREAD

**Issue by kuzetsa** [GKernelCI/GBuildbot#71]
current state of amd64:

1. kernel source is compiled
2. kernel image is passed to a wrapper
3. qemu is used to boot a disk image  
(*gentoo stable profile / a real OS*)

rather than a minimalist test, arm should boot a  
stable profile / realistic OS (*more than busybox*)

**Comment by kuzetsa** [comment]
work on #52 and/or #62 was stalled because there  
wasn't suitable development hardware available, but  
it should be possible to pool resources with @mjeveritt  
to move forward.

will be using github "issues" and/or kanban-type project  
tracking tools for collaboration (*transparency*) and  
transferring the documentation to a gentoo-managed  
wiki / project space / Gentoo_kernelCI should be easier  
if the workflow is tracked in a more public & visible way.

*...rather than an undocumented, quick & dirty "hack"*

**Comment by aliceinwire** [comment]
thanks, looks interesting.

**Comment by aliceinwire** [comment]
we implemented a gentoo stage3 for testing the gentoo-sources kernel
